src/components/wrecksList.jsx

Hylkyjen järjestäminen aakkosjärjestykseen.

Wrecklist in alphabetical order

---

cypress/integration/home_page_spec.js
cypress/integration/wrecks_page_spec.js

Testejä lomakkeen täytölle. Oikeastaan nää kuuluisi wreck_page -testeihin jotka on J-P:n pullarissa.

cypress tests for notification form filling

---

src/components/NotificationForm.jsx
src/components/notificationForm.test.jsx
src/components/wrecksList.test.jsx

En nyt valitettavasti ehdi tän enempää tekeen unittestejä tässä sprintissä, mutta on nyt jotain aloitettu...Aika paljon ongelmia mockkaamisen kanssa ja suurin osa ajasta mennyt dokumentaation lukemiseen kun en ole aikasemmin jestiä käyttänyt

jest start

---

package-lock.json
package.json
src/App.jsx
src/components/Navigation.jsx
src/components/NewTargetForm.jsx
src/hooks/useNewTargetForm.jsx

lisätty sivu uuden hylyn lisäämiselle

newTargetPage

---

src/components/NewTargetForm.jsx

Muokattu hylynlisäyskaavakkeen visuaalista ilmettä

Edit form visual layout

---

cypress/integration/dive_notification_page_spec.js
cypress/integration/targets_page_spec.js

Selaintestien päivittelyä ja vähän uudelleennimeämistä.

form cypress tests updating

---

src/components/TargetPage/TargetInfo.jsx
src/tests/targetPage/target_info.test.js

Hylky-sivulla Kunta -> Alue (koska omissa ilmoituksissa tässä kentässä on Vesialue/lähisaari)

Change kunta to alue in target page and fix tests

---

src/components/NewTargetForm.jsx
src/components/NotificationForm.jsx
src/components/TargetPage/TargetInfo.jsx
src/components/TargetPage/TargetLocationMap.jsx
src/components/TargetPage/TargetPage.jsx
src/components/TargetsList.jsx

Kaikki sivut muutettu skaalautumaan sopivaksi mobiililaitteille

Responsiveness

---

src/components/MainMap.jsx

Nappi karttaan myös käyttäjien tekemille kohteille.
Itse popupin sisältö kysytään seuraavassa asiakastapaamisessa niin se on ennallaan.

Button on all markers

---

src/components/MainMap.jsx

fix mobile map button

---

cypress/integration/home_page_spec.js

Improve map testing

---

src/assets/styles/App.css
src/components/Navigation.jsx
src/components/TargetList/SearchBar.jsx

Hakukenttä näyttää nyt paremmalta mobiilissa.
Navbar ei jää enää auki, kun siitä klikataan toiselle sivulle.

fix search responsiveness and collapse nav on click

---

cypress/integration/newtarget_page_spec.js
src/hooks/useNewTargetForm.jsx

https://github.com/Sukellusilmoitus/backend/pull/24
Backin pullariin liittyvä pieni muutos hylkylomakkeen lähettämiseen. Mukana uusi muuttuja.

is_pending property added for new target

---

src/components/TargetPage/DiveHistory.jsx
src/components/TargetPage/index.jsx

add loadingspinner for dive history

---

cypress/integration/dive_notification_page_spec.js
package-lock.json
package.json
src/components/NewNotificationForm.jsx
src/components/NewNotificationForm.test.jsx
src/components/TargetPage/TargetPage.jsx
src/hooks/useNewNotificationForm.jsx
src/hooks/useNewTargetForm.jsx

Tähän jäi jotain async bugeja mitä en osannut korjata, joten en implementoinut komponentteja muuhun koodiin.

validationHooks

---

cypress/integration/home_page_spec.js
package-lock.json
package.json
src/components/MainMap.jsx

Kartta muistaa siis nyt tilansa aina

MapPersistsAlways

---

cypress/integration/dive_notification_page_spec.js
src/components/CoordinatesMap.jsx
src/components/NotificationForm.jsx
src/components/TargetPage/TargetPage.jsx
src/hooks/useNewNotificationForm.jsx

started coordinatesMap feature

coordinatesMap

---

cypress/integration/dive_notification_page_spec.js
package-lock.json
package.json
src/components/NotificationForm.jsx
src/components/TargetPage/DiveHistory.jsx

Sukellushistoriasta loput piiloon jos on paljon sukelluksia. Napista saa kaikki sukellukset näkyville.

Dive notification history wrap

---

src/App.jsx
src/components/AdminPanel/ReactAdmin.jsx
src/components/Login.jsx
src/components/Navigation.jsx
src/components/Register.jsx
src/services/users.js

Rekisteröinti sivu, vaatii toimiakseen backendin login ja register pull requestit.

Register page

---

cypress/integration/login_page_spec.js
cypress/integration/register_page_spec.js
src/components/Login.jsx
src/components/Login.test.jsx
src/components/Register.jsx
src/components/Register.test.js

- E2E & unit testit kirjautuminen + rekisteröinti

Account login / register test

---

cypress/integration/feedback_spec.js
package-lock.json
package.json
src/App.jsx
src/components/Feedback/Feedback.jsx
src/components/Feedback/Feedback.test.js
src/components/Feedback/FeedbackForm.jsx
src/components/Feedback/FeedbackForm.test.js
src/components/Feedback/index.jsx
src/components/Navigation.jsx
src/components/Navigation.test.jsx
src/components/PageTitle.jsx
src/components/PageTitle.test.js
src/components/TargetList/index.jsx
src/services/feedbacks.js

Lisää frontiin palautelomakkeen. Vaatii backin [tämän](https://github.com/Sukellusilmoitus/backend/pull/38) pullarin toimiakseen.

Give feedback

---

src/components/NewTargetForm.jsx
src/components/NotificationForm.jsx
src/hooks/useNewNotificationForm.jsx
src/hooks/useNewTargetForm.jsx

näyttää uudet koordinaatit kartan yläreunassa DMS muodossa

showNewCoordsDMS

---

src/App.jsx
src/components/Logout.jsx
src/components/Logout.test.jsx
src/components/Navigation.jsx
src/components/Navigation.test.jsx

- Uloskirjautumislinkki navbarissa
- Ehdollinen renderöinti komponenteille navbarissa
- Yksikkötestaus Logout ja Navigation -komponenteille

Logout link on navbar with unit tests

---

src/components/UserPage/UserInfo.jsx
src/components/UserPage/UserInfo.test.js
src/components/UserPage/UserPage.jsx
src/components/UserPage/UserPage.test.js
src/services/users.js

- Kirjautunut käyttäjä voi päivittää puh/spostin/nimen
- Päivittää auth-tokeniin uudet tiedot

Update user data

---

cypress/integration/register_page_spec.js
src/components/Home.jsx
src/components/Home.test.jsx
src/components/Login.jsx
src/components/Login.test.jsx
src/components/NewTargetForm.jsx
src/components/PageTitle.jsx
src/components/Register.jsx
src/components/Register.test.js
src/components/TargetPage/TargetPage.jsx
src/components/UserPage/UserPage.jsx
src/components/UserPage/UserPage.test.js

Kaikilla sivuilla nyt yhtenäisempi otsikko ja sivun yläosa.

Add uniform titles to all pages

---

cypress/integration/user_page_spec.js

e2e testaus, kattavampi testaus yksikkötesteissä

Add cypress tests

---

cypress/integration/dive_notification_page_spec.js
src/components/NewTargetForm.jsx
src/components/NewTargetForm.test.jsx
src/components/NotificationForm.jsx
src/components/NotificationForm.test.jsx

jest testit lomakkeiden automaattiselle täytölle

autoFillTests

---

src/components/Login.test.jsx
src/components/TargetPage/index.jsx
src/components/TargetPage/index.test.js

Force window scroll position to top

---

package-lock.json
package.json
public/index.html
src/App.jsx
src/components/AdminPanel/AdminPanel.jsx
src/components/Feedback/Feedback.jsx
src/components/Login.jsx
src/components/NewTargetForm.jsx
src/components/Register.jsx
src/components/TargetList/index.jsx
src/components/TargetPage/TargetInfo.jsx
src/components/TargetPage/index.jsx
src/components/UserPage/index.jsx

Lisätty sivuille yksilölliset titlet ja meta descriptionit. Lisäksi vaihdettu ulkoiset linkit aukeamaan uuteen välilehteen.

Meta information

---

package-lock.json
package.json
public/index.html
src/App.jsx
src/components/AdminPanel/AdminPanel.jsx
src/components/Feedback/Feedback.jsx
src/components/Login.jsx
src/components/NewTargetForm.jsx
src/components/Register.jsx
src/components/TargetList/index.jsx
src/components/TargetPage/TargetInfo.jsx
src/components/TargetPage/index.jsx
src/components/UserPage/index.jsx

Meta information 2

---

src/components/UserPage/index.jsx
src/services/dives.js
src/services/targets.js

Vaatii [backing pr 57](https://github.com/Sukellusilmoitus/backend/pull/57)

Add token to request
